// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package edu.buaa.act.jcsindex.global.proto;

public final class BroadcastProto {
  private BroadcastProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BroadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.BroadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 timeIndex = 1;</code>
     */
    int getTimeIndex();

    /**
     * <code>int64 leftBound = 2;</code>
     */
    long getLeftBound();

    /**
     * <code>int64 rightBound = 3;</code>
     */
    long getRightBound();
  }
  /**
   * Protobuf type {@code proto.BroadRequest}
   */
  public  static final class BroadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.BroadRequest)
      BroadRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BroadRequest.newBuilder() to construct.
    private BroadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadRequest() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BroadRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timeIndex_ = input.readInt32();
              break;
            }
            case 16: {

              leftBound_ = input.readInt64();
              break;
            }
            case 24: {

              rightBound_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BroadcastProto.internal_static_proto_BroadRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BroadcastProto.internal_static_proto_BroadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BroadcastProto.BroadRequest.class, BroadcastProto.BroadRequest.Builder.class);
    }

    public static final int TIMEINDEX_FIELD_NUMBER = 1;
    private int timeIndex_;
    /**
     * <code>int32 timeIndex = 1;</code>
     */
    public int getTimeIndex() {
      return timeIndex_;
    }

    public static final int LEFTBOUND_FIELD_NUMBER = 2;
    private long leftBound_;
    /**
     * <code>int64 leftBound = 2;</code>
     */
    public long getLeftBound() {
      return leftBound_;
    }

    public static final int RIGHTBOUND_FIELD_NUMBER = 3;
    private long rightBound_;
    /**
     * <code>int64 rightBound = 3;</code>
     */
    public long getRightBound() {
      return rightBound_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeIndex_ != 0) {
        output.writeInt32(1, timeIndex_);
      }
      if (leftBound_ != 0L) {
        output.writeInt64(2, leftBound_);
      }
      if (rightBound_ != 0L) {
        output.writeInt64(3, rightBound_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timeIndex_);
      }
      if (leftBound_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, leftBound_);
      }
      if (rightBound_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rightBound_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BroadcastProto.BroadRequest)) {
        return super.equals(obj);
      }
      BroadcastProto.BroadRequest other = (BroadcastProto.BroadRequest) obj;

      if (getTimeIndex()
          != other.getTimeIndex()) return false;
      if (getLeftBound()
          != other.getLeftBound()) return false;
      if (getRightBound()
          != other.getRightBound()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMEINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getTimeIndex();
      hash = (37 * hash) + LEFTBOUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeftBound());
      hash = (37 * hash) + RIGHTBOUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRightBound());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BroadcastProto.BroadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BroadcastProto.BroadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BroadcastProto.BroadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.BroadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.BroadRequest)
        BroadcastProto.BroadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BroadcastProto.internal_static_proto_BroadRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BroadcastProto.internal_static_proto_BroadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BroadcastProto.BroadRequest.class, BroadcastProto.BroadRequest.Builder.class);
      }

      // Construct using edu.buaa.act.jcsindex.global.proto.BroadcastProto.BroadRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        timeIndex_ = 0;

        leftBound_ = 0L;

        rightBound_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BroadcastProto.internal_static_proto_BroadRequest_descriptor;
      }

      @Override
      public BroadcastProto.BroadRequest getDefaultInstanceForType() {
        return BroadcastProto.BroadRequest.getDefaultInstance();
      }

      @Override
      public BroadcastProto.BroadRequest build() {
        BroadcastProto.BroadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BroadcastProto.BroadRequest buildPartial() {
        BroadcastProto.BroadRequest result = new BroadcastProto.BroadRequest(this);
        result.timeIndex_ = timeIndex_;
        result.leftBound_ = leftBound_;
        result.rightBound_ = rightBound_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BroadcastProto.BroadRequest) {
          return mergeFrom((BroadcastProto.BroadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BroadcastProto.BroadRequest other) {
        if (other == BroadcastProto.BroadRequest.getDefaultInstance()) return this;
        if (other.getTimeIndex() != 0) {
          setTimeIndex(other.getTimeIndex());
        }
        if (other.getLeftBound() != 0L) {
          setLeftBound(other.getLeftBound());
        }
        if (other.getRightBound() != 0L) {
          setRightBound(other.getRightBound());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BroadcastProto.BroadRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BroadcastProto.BroadRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int timeIndex_ ;
      /**
       * <code>int32 timeIndex = 1;</code>
       */
      public int getTimeIndex() {
        return timeIndex_;
      }
      /**
       * <code>int32 timeIndex = 1;</code>
       */
      public Builder setTimeIndex(int value) {

        timeIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 timeIndex = 1;</code>
       */
      public Builder clearTimeIndex() {

        timeIndex_ = 0;
        onChanged();
        return this;
      }

      private long leftBound_ ;
      /**
       * <code>int64 leftBound = 2;</code>
       */
      public long getLeftBound() {
        return leftBound_;
      }
      /**
       * <code>int64 leftBound = 2;</code>
       */
      public Builder setLeftBound(long value) {

        leftBound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 leftBound = 2;</code>
       */
      public Builder clearLeftBound() {

        leftBound_ = 0L;
        onChanged();
        return this;
      }

      private long rightBound_ ;
      /**
       * <code>int64 rightBound = 3;</code>
       */
      public long getRightBound() {
        return rightBound_;
      }
      /**
       * <code>int64 rightBound = 3;</code>
       */
      public Builder setRightBound(long value) {

        rightBound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rightBound = 3;</code>
       */
      public Builder clearRightBound() {

        rightBound_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.BroadRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.BroadRequest)
    private static final BroadcastProto.BroadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BroadcastProto.BroadRequest();
    }

    public static BroadcastProto.BroadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadRequest>
        PARSER = new com.google.protobuf.AbstractParser<BroadRequest>() {
      @Override
      public BroadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BroadRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BroadRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public BroadcastProto.BroadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BroadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.BroadResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string dests = 1;</code>
     */
    java.util.List<String>
        getDestsList();
    /**
     * <code>repeated string dests = 1;</code>
     */
    int getDestsCount();
    /**
     * <code>repeated string dests = 1;</code>
     */
    String getDests(int index);
    /**
     * <code>repeated string dests = 1;</code>
     */
    com.google.protobuf.ByteString
        getDestsBytes(int index);
  }
  /**
   * Protobuf type {@code proto.BroadResponse}
   */
  public  static final class BroadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.BroadResponse)
      BroadResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BroadResponse.newBuilder() to construct.
    private BroadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadResponse() {
      dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BroadResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dests_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              dests_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dests_ = dests_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BroadcastProto.internal_static_proto_BroadResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BroadcastProto.internal_static_proto_BroadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BroadcastProto.BroadResponse.class, BroadcastProto.BroadResponse.Builder.class);
    }

    public static final int DESTS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList dests_;
    /**
     * <code>repeated string dests = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDestsList() {
      return dests_;
    }
    /**
     * <code>repeated string dests = 1;</code>
     */
    public int getDestsCount() {
      return dests_.size();
    }
    /**
     * <code>repeated string dests = 1;</code>
     */
    public String getDests(int index) {
      return dests_.get(index);
    }
    /**
     * <code>repeated string dests = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDestsBytes(int index) {
      return dests_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dests_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dests_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < dests_.size(); i++) {
          dataSize += computeStringSizeNoTag(dests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDestsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BroadcastProto.BroadResponse)) {
        return super.equals(obj);
      }
      BroadcastProto.BroadResponse other = (BroadcastProto.BroadResponse) obj;

      if (!getDestsList()
          .equals(other.getDestsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDestsCount() > 0) {
        hash = (37 * hash) + DESTS_FIELD_NUMBER;
        hash = (53 * hash) + getDestsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BroadcastProto.BroadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BroadcastProto.BroadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BroadcastProto.BroadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BroadcastProto.BroadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BroadcastProto.BroadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.BroadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.BroadResponse)
        BroadcastProto.BroadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BroadcastProto.internal_static_proto_BroadResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BroadcastProto.internal_static_proto_BroadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BroadcastProto.BroadResponse.class, BroadcastProto.BroadResponse.Builder.class);
      }

      // Construct using edu.buaa.act.jcsindex.global.proto.BroadcastProto.BroadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BroadcastProto.internal_static_proto_BroadResponse_descriptor;
      }

      @Override
      public BroadcastProto.BroadResponse getDefaultInstanceForType() {
        return BroadcastProto.BroadResponse.getDefaultInstance();
      }

      @Override
      public BroadcastProto.BroadResponse build() {
        BroadcastProto.BroadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BroadcastProto.BroadResponse buildPartial() {
        BroadcastProto.BroadResponse result = new BroadcastProto.BroadResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          dests_ = dests_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dests_ = dests_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BroadcastProto.BroadResponse) {
          return mergeFrom((BroadcastProto.BroadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BroadcastProto.BroadResponse other) {
        if (other == BroadcastProto.BroadResponse.getDefaultInstance()) return this;
        if (!other.dests_.isEmpty()) {
          if (dests_.isEmpty()) {
            dests_ = other.dests_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDestsIsMutable();
            dests_.addAll(other.dests_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BroadcastProto.BroadResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BroadcastProto.BroadResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDestsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dests_ = new com.google.protobuf.LazyStringArrayList(dests_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDestsList() {
        return dests_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public int getDestsCount() {
        return dests_.size();
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public String getDests(int index) {
        return dests_.get(index);
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDestsBytes(int index) {
        return dests_.getByteString(index);
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public Builder setDests(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDestsIsMutable();
        dests_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public Builder addDests(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDestsIsMutable();
        dests_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public Builder addAllDests(
          Iterable<String> values) {
        ensureDestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dests_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public Builder clearDests() {
        dests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dests = 1;</code>
       */
      public Builder addDestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDestsIsMutable();
        dests_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.BroadResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.BroadResponse)
    private static final BroadcastProto.BroadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BroadcastProto.BroadResponse();
    }

    public static BroadcastProto.BroadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadResponse>
        PARSER = new com.google.protobuf.AbstractParser<BroadResponse>() {
      @Override
      public BroadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BroadResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BroadResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public BroadcastProto.BroadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BroadRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BroadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BroadResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BroadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017broadcast.proto\022\005proto\"H\n\014BroadRequest" +
      "\022\021\n\ttimeIndex\030\001 \001(\005\022\021\n\tleftBound\030\002 \001(\003\022\022" +
      "\n\nrightBound\030\003 \001(\003\"\036\n\rBroadResponse\022\r\n\005d" +
      "ests\030\001 \003(\t2H\n\017BroadcastSearch\0225\n\006search\022" +
      "\023.proto.BroadRequest\032\024.proto.BroadRespon" +
      "se\"\000B4\n\"edu.buaa.act.jcsindex.global.pro" +
      "toB\016BroadcastProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_BroadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_BroadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BroadRequest_descriptor,
        new String[] { "TimeIndex", "LeftBound", "RightBound", });
    internal_static_proto_BroadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_BroadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BroadResponse_descriptor,
        new String[] { "Dests", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
